env:
  browser: true
  es6: true
  jest: true
extends: 'airbnb-base'
parserOptions:
  sourceType: module
rules:
  import/prefer-default-export: off
  camelcase: off
  import/no-unresolved: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-dynamic-require: off
  no-new: off
  no-console: off
  global-require: off
  indent:
    - error
    - 2
  no-underscore-dangle: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  comma-dangle:
    - warn
    - always-multiline
  semi:
    - error
    - never
settings:
  import/resolver:
    babel-module:
      - src
      - __test__
