env:
  browser: true
  es6: true
extends: 'airbnb-base'
parserOptions:
  sourceType: module
rules:
  import/prefer-default-export:
    - off
  import/no-extraneous-dependencies:
    - off
  no-console:
    - off
  indent:
    - error
    - 2
  no-underscore-dangle:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  comma-dangle:
    - warn
    - always-multiline
  semi:
    - error
    - never
settings:
  import/resolver:
    babel-module: src
